services:
  redis:
    image: redis:7.2.4
    restart: no
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - tednews-network
  channels-micro:
    build: ./services/channels/
    restart: no
    ports:
      - '8081:8080'
    networks:
      - tednews-network
    depends_on:
      - redis
volumes:
  cache:
    driver: local
networks:
  tednews-network:
    external: true      