version: '3.8'

services:
  redis:
    image: redis:7.2.4
    restart: no
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  channels-micro:
    image: mcr.microsoft.com/devcontainers/go:1.22
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - "redis"
    depends_on:
      - redis
volumes:
  cache:
    driver: local